"""initial database migration

Revision ID: 071705910d6c
Revises: b31c2b61d88d
Create Date: 2021-03-12 00:35:01.378548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071705910d6c'
down_revision = 'b31c2b61d88d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_address', sa.Column('city', sa.String(length=30), nullable=True))
    op.add_column('ip_address', sa.Column('continent_name', sa.String(length=30), nullable=True))
    op.add_column('ip_address', sa.Column('country_code', sa.String(length=5), nullable=True))
    op.add_column('ip_address', sa.Column('country_name', sa.String(length=30), nullable=True))
    op.add_column('ip_address', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('ip_address', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('ip_address', sa.Column('region_code', sa.String(length=30), nullable=True))
    op.add_column('ip_address', sa.Column('region_name', sa.String(length=30), nullable=True))
    op.add_column('ip_address', sa.Column('zip', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ip_address', 'zip')
    op.drop_column('ip_address', 'region_name')
    op.drop_column('ip_address', 'region_code')
    op.drop_column('ip_address', 'longitude')
    op.drop_column('ip_address', 'latitude')
    op.drop_column('ip_address', 'country_name')
    op.drop_column('ip_address', 'country_code')
    op.drop_column('ip_address', 'continent_name')
    op.drop_column('ip_address', 'city')
    # ### end Alembic commands ###
