"""initial database migration

Revision ID: b31c2b61d88d
Revises: 
Create Date: 2021-03-11 23:17:02.512588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b31c2b61d88d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('type', sa.String(length=4), nullable=False),
    sa.Column('continent_code', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ip_address')
    # ### end Alembic commands ###
